import { TMenuItem } from '../../../docs/components/docs-menu/docs-menu';

export const DEMOS_MENU_ITEMS: TMenuItem[] = [
  {
    route: 'accordion',
    title: 'Accordion',
    isActive: false,
    level: 0,
  },
  {
    route: 'bar-chart',
    title: 'BarChart',
    isActive: false,
    level: 0,
  },
  {
    route: 'button',
    title: 'Button',
    isActive: false,
    level: 0,
  },
  {
    route: 'checkbox',
    title: 'Checkbox',
    isActive: false,
    level: 0,
  },
  {
    route: 'date-picker',
    title: 'DatePicker',
    isActive: false,
    level: 0,
  },
  {
    route: 'dropdown',
    title: 'Dropdown',
    isActive: false,
    level: 0,
  },
  {
    route: 'file-picker',
    title: 'FilePicker',
    isActive: false,
    level: 0,
  },
  {
    route: 'input',
    title: 'Input',
    isActive: false,
    level: 0,
  },
  {
    route: 'line-chart',
    title: 'LineChart',
    isActive: false,
    level: 0,
  },
  {
    route: 'list',
    title: 'List',
    isActive: false,
    level: 0,
  },
  {
    route: 'lookup',
    title: 'Lookup',
    isActive: false,
    level: 0,
  },
  {
    route: 'notification',
    title: 'Notification',
    isActive: false,
    level: 0,
  },
  {
    route: 'numberbox',
    title: 'Numberbox',
    isActive: false,
    level: 0,
  },
  {
    route: 'pie-chart',
    title: 'PieChart',
    isActive: false,
    level: 0,
  },
  {
    route: 'popup',
    title: 'Popup',
    isActive: false,
    level: 0,
  },
  {
    route: 'radio-group',
    title: 'RadioGroup',
    isActive: false,
    level: 0,
  },
  {
    route: 'scroll-layout',
    title: 'ScrollLayout',
    isActive: false,
    level: 0,
  },
  {
    route: 'slide-toggle',
    title: 'SlideToggle',
    isActive: false,
    level: 0,
  },
  {
    route: 'slider',
    title: 'Slider',
    isActive: false,
    level: 0,
  },
  {
    route: 'slider-item',
    title: 'SliderItem',
    isActive: false,
    level: 0,
  },
  {
    route: 'spinner',
    title: 'Spinner',
    isActive: false,
    level: 0,
  },
  {
    route: 'table',
    title: 'Table',
    isActive: false,
    level: 0,
  },
  {
    route: 'tabs',
    title: 'Tabs',
    isActive: false,
    level: 0,
  },
  {
    route: 'textarea',
    title: 'Texarea',
    isActive: false,
    level: 0,
  },
  {
    route: 'tooltip',
    title: 'Tooltip',
    isActive: false,
    level: 0,
  },
];
